sonar.projectKey=Csontikka_esphome-tailscale
sonar.organization=csontikka
sonar.projectName=esphome-tailscale

sonar.sources=components/tailscale
sonar.inclusions=**/*.py
sonar.exclusions=**/microlink/**,**/.esphome/**,**/*.cpp,**/*.h

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
